site_name: NIST 800-53 Playbook
nav:
    - Access Control: 
        - AC-1: ac/ac-1.md
    - About: about.md
    
copyright: Copyright &copy; 2023 Washington GT.
    
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
    
theme: 
    name: material
    features:
        - content.tabs.link

#### list of themes ####
## material
## theme: readthedocs

extra:
  analytics:
    provider: google
    property: G-FVH8RBS1KG